### PR TITLE
Update ldap.py with auth search scope subtree capability ii

### PR DESCRIPTION
**Pull request by ds-04**
Update ldap.py with auth search scope subtree capability ii

signed off

### CODE REVIEW

**Comment by aebruno** [comment]
@ds-04 This looks great. Can you add this new option to the documentation. Add it to this section [here](https://github.com/ubccr/coldfront/blob/main/docs/pages/config.md#ldap-auth).

**Comment by ds-04** [comment]
> @ds-04 This looks great. Can you add this new option to the documentation. Add it to this section [here](https://github.com/ubccr/coldfront/blob/main/docs/pages/config.md#ldap-auth).

thanks now done

**Comment by aebruno** [comment]
Looks great. One last thing, can you git rebase this down to a single commit? Then should be good to merge. Thanks again!

**Comment by aebruno** [comment]
Looks like your commit is missing `--signoff`. Sorry to be a pain.

**Comment by ds-04** [comment]
ok apologies for that... should be signed off now

overwrote using a force push from my feature branch... looks ok i think

**Review by aebruno — APPROVED** [review]

**Pull request merged**
