### PR TITLE
Research Output Report Added

### PR DESCRIPTION
**Pull request by ShreyasSridhar24**
Solves #494. A Research Output report is now added under the _Director_ dropdown menus for centre directors to view Research Outputs in a tabulated format. This can be exported as a `.csv` file similar to the grant report.

This report is also available under the _Staff_ menu, only if the user has the `Can view research output report` permission enabled for them.

### CODE REVIEW

**Review by dsajdak — CHANGES_REQUESTED** [review]
@ShreyasSridhar24 this report is great!  I can see it from the admin menu and tested it with a few combinations of research output added to the projects.  Funny thing is, I'm actually not sure how to get to the Director menu.  I see the file you've edited but I'm not sure how to display that.  Currently, we set the "Director" role with a bunch of extra permissions to view things like "all projects", the "pending project review" list, and the "grant report/list" but these all fall under the Staff menu which the "director" user can see.  This is [documented here](https://coldfront.readthedocs.io/en/latest/howto/roles/director/).  If you try this out with the test data you'll be able to see this.  I tried adding an additional permission ("research output|can view research output") to my test user but that didn't allow this report to show up on the Staff menu.  How did you get the director menu to come up?  I'm wondering if this is leftover from a long time ago and we never removed it.

**Comment by millie-aka** [comment]
@ShreyasSridhar24 
Hi Shreyas,
 I am trying to make changes to the code so that I can add an extra field 'FOR Code' in the 'Create Project'. I have create 'for_code' app similar to 'field_of_science' app. However, on making change in the file /coldfront/core/project/views.py in line number 454 like this ->
    fields = ['title', 'description', 'field_of_science', 'fas_code',]
I am getting error. I have just started learning Django and have been assigned to this task. Could you please provide some guidance.
Thank you

**Comment by dsajdak** [comment]
@millie-aka I replied to you via email.  Please create new issues for bug reports, if you have them, rather than commenting on open pull requests for other features.  Thanks!

**Review by dsajdak — APPROVED** [review]
LGTM!

**Pull request closed without merging**
