### PR TITLE
Fix deletion of invoice notes

### PR DESCRIPTION
**Pull request by zooley**
A couple minor HTML fixes and two changes that were preventing deletion of invoice notes.

### CODE REVIEW

**Comment by dsajdak** [comment]
@zooley I'm not able to replicate the issue with deleting the invoice notes, unless you're talking about after the allocation is in 'paid' status.  Can you just let me know your process so I can try to replicate before we merge this PR?

**Comment by zooley** [comment]
How long are your notes? All the issues popped up due to the form having `max_length=64` for the `note` field. If I added a note longer than 64 characters, which is allowable as the database column is a TEXT field, and then tried to delete the note from the invoice page, the `if formset.is_valid()` check would always return false (due to the `note` being longer than 64 characters). This, in turn, would cause an error to get thrown because the `return HttpResponseRedirect(...)` line is nested under that `if` statement and the method would return `null` (and the method requires an `HttpResponse` is returned).

**Comment by dsajdak** [comment]
Ah, yeah I missed that part.  Yep, I can replicate the problem.  Thanks for the fix!

**Comment by aebruno** [comment]
Thank you!

**Pull request merged**
